# Generated by Django 4.2 on 2023-05-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="researchPaper",
            field=models.FileField(default="", max_length=250, null=True, upload_to=""),
        ),
    ]
